trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: AZURE_STATIC_WEB_APPS_API_TOKEN
    value: 'a8afead21aa39bd4ce844c1bfedfe1c4ff730d2cea4b1827355790213d8b92025-0add310a-9ff3-4222-903c-456779b5daaf00f214390'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run pregenerate-dev-api && npm run apigen
  displayName: 'Generate API Client'

- script: |
    npm run build
  displayName: 'Build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/' # Assuming root is where your app is built
    api_location: 'api' # Adjust based on your project structure
    output_location: 'dist' # Output directory from Vite build
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
  displayName: 'Deploy to Azure Static Web App'
